### ISSUE TITLE
Taking more time to detect the edges 

### ISSUE THREAD

**Issue by shaliniqsg** [charlymr/IRLDocumentScanner#26]
Hi Denis,

We are successfully able to integrate your framework into our application.
We are happy with this framework and I would like to share some feedback on this,
We have noticed some of the issues : 
1.Some times it will take more time to detect the edges .
2.Some times even though we hold it steadily it will not yet all detect the edges.
3.In order to detect the edges we should hold it exactly .
4.Document is not captured, if device is holded in vertical position with respect to document.
5.Document is not captured, if device is holded in semi horizontal position with respect to document.
6.Document is not captured if device is holded far from the device.
7.Document is not captured if edges are not detected by the device.
8.If the position is not steady document captured is blurred.
9.Document is not captured fully if there is black border in the document.(Black border is considered as edges).

Please help us to improve this library.
Thanks in advance .
Shalini

**Comment by charlymr** [comment]
Hi @shaliniqsg,

Thanks for reading out. The Framework leveraging and Apple Framework to detect border, therefore unless we embed a custom made framework (which is not the purpose of that library) I don't think we can do much more than that.

Regarding the hold ready, or device position, I am providing this framework as an open source (free of charge) project and therefore would be happy to get it to work better, however, time is missing right now as I am working on other projects. 

I think this is a great idea to stabilise the image capture and the community and I would love to see some improvements on that part. Maybe you could come up with something and share it with us since you are using the library, it's only fair that you give back 👍 

The process is straight forward, Fork this repo, make as much changes as you want to it (so it fit your needs, please try to bare in mind you need to keep compatibility) then create a pull request. I will review and happily merge it to this project.

Thanks,

Denis
