### ISSUE TITLE
IRLDocumentScanner crashed!!

### ISSUE THREAD

**Issue by keyur4707** [charlymr/IRLDocumentScanner#38]
crashing application at jpegStillImageNSDataRepresentation. please rectify this and we are not on slow internet.

<img width="1121" alt="Screenshot 2021-03-30 at 12 36 34 PM" src="https://user-images.githubusercontent.com/31365552/112947674-b8e18580-9154-11eb-897c-64147f802808.png">
![Uploading Screenshot 2021-03-30 at 12.37.01 PM.png…]()

**Comment by charlymr** [comment]
First, hello @keyur4707 

I am don't have much time those day to work on this project. And without more context it's very hard to actually know what happen. 

Just as a reminder of Open Source concept, it come with no warranties, nor with support, the idea is that people working on open source project do it for free and if someone find a bug, they usually try to get into the code and eventually fix it then create a pull request as a contribution to the overall project itself.

Please do not hesitate to create a PR if you find the root cause of the crash. So other people who use the code freely, like you, can take advantage from it. 

If you cannot or do not want to do it and still feel that the vendor should fix the issue for you, I suggest you search for a commercial alternative.

Kind regards,

Denis
